export const edModules = [
    {
        "title": "Recognizing Heart Attack Symptoms",
        "content": "A heart attack, or myocardial infarction, occurs when the blood flow to a part of the heart is blocked for a long enough time that part of the heart muscle is damaged or dies.\nRecognizing the symptoms early can be life-saving.\nCommon signs include chest pain or discomfort, which may feel like pressure, squeezing, fullness, or pain, and may last for more than a few minutes or come and go.\nOther symptoms include shortness of breath, nausea, lightheadedness, cold sweat, and discomfort in other areas of the upper body such as the arms, back, neck, jaw, or stomach.\nWomen may experience symptoms differently, often feeling more of a sharp pain or burning in the chest, pain in the back, neck, jaw, or stomach, shortness of breath, and nausea.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Identifying Signs of Stroke",
        "content": "A stroke occurs when the blood supply to part of the brain is interrupted or reduced, preventing brain tissue from getting oxygen and nutrients.\nEarly action can minimize brain damage and potential complications.\nThe acronym FAST helps remember the warning signs: Face drooping, Arm weakness, Speech difficulty, and Time to call emergency services.\nOther signs include sudden numbness or weakness of the face, arm, or leg, especially on one side of the body, sudden confusion, trouble speaking, or understanding speech, sudden trouble seeing in one or both eyes, sudden trouble walking, dizziness, loss of balance or coordination, and sudden severe headache with no known cause.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Understanding Symptoms of Diabetic Emergencies",
        "content": "Diabetic emergencies, such as hypoglycemia (low blood sugar) and hyperglycemia (high blood sugar), require immediate attention.\nHypoglycemia symptoms include shakiness, sweating, confusion, irritability, rapid heartbeat, dizziness, and seizures.\nHyperglycemia symptoms include high levels of sugar in the blood, frequent urination, increased thirst, blurred vision, fatigue, and fruity-smelling breath.\nSevere cases can lead to diabetic ketoacidosis (DKA) with symptoms like nausea, vomiting, abdominal pain, and unconsciousness.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Detecting Asthma Attacks",
        "content": "Asthma attacks occur when the airways narrow, swell, and produce extra mucus, making it difficult to breathe.\nSymptoms include severe shortness of breath, chest tightness or pain, coughing or wheezing, and rapid breathing.\nIn severe cases, symptoms worsen quickly, and the use of rescue inhalers becomes more frequent and less effective.\nBlue lips or fingernails indicate a severe attack needing immediate medical attention.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Spotting Signs of Seizures",
        "content": "Seizures are sudden, uncontrolled electrical disturbances in the brain.\nSymptoms vary but can include temporary confusion, staring spells, uncontrollable jerking movements of the arms and legs, loss of consciousness or awareness, and cognitive or emotional symptoms like fear, anxiety, or déjà vu.\nRecognizing and responding appropriately can help ensure safety during the episode.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Identifying Symptoms of Severe Allergic Reactions (Anaphylaxis)",
        "content": "Anaphylaxis is a severe, potentially life-threatening allergic reaction that can occur within seconds or minutes of exposure to an allergen.\nSymptoms include skin reactions such as hives and itching, flushed or pale skin, low blood pressure, constriction of airways, swollen tongue or throat causing wheezing and trouble breathing, a weak and rapid pulse, nausea, vomiting, diarrhea, and dizziness or fainting.\nImmediate administration of epinephrine and calling emergency services are crucial.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Recognizing Symptoms of Heat Stroke and Heat Exhaustion",
        "content": "Heat exhaustion and heat stroke are serious conditions caused by prolonged exposure to high temperatures and dehydration.\nHeat exhaustion symptoms include heavy sweating, cold, pale, and clammy skin, fast, weak pulse, nausea or vomiting, muscle cramps, tiredness or weakness, dizziness, headache, and fainting.\nHeat stroke is more severe, with symptoms such as high body temperature (104°F or higher), hot, red, dry, or damp skin, a fast, strong pulse, headache, dizziness, nausea, confusion, and unconsciousness.\nImmediate cooling and hydration are vital, and heat stroke requires emergency medical attention.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Identifying Signs of Hypothermia",
        "content": "Hypothermia occurs when the body loses heat faster than it can produce, causing dangerously low body temperatures.\nSymptoms include shivering, exhaustion, confusion, fumbling hands, memory loss, slurred speech, and drowsiness.\nIn severe cases, shivering may stop, the person may become unconscious, and there could be a slow, weak pulse.\nImmediate warming of the body and medical attention are essential.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Detecting Symptoms of Poisoning",
        "content": "Poisoning can result from ingesting, inhaling, touching, or injecting harmful substances.\nSymptoms vary widely depending on the type and amount of poison but can include nausea, vomiting, diarrhea, stomach pain, difficulty breathing, confusion, drowsiness, seizures, and loss of consciousness.\nIdentifying the substance and seeking immediate medical help is crucial.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Understanding Symptoms of Meningitis",
        "content": "Meningitis is an inflammation of the membranes surrounding the brain and spinal cord, often caused by an infection.\nSymptoms include sudden high fever, stiff neck, severe headache that seems different from normal, nausea or vomiting, confusion or difficulty concentrating, seizures, sleepiness or difficulty waking, sensitivity to light, and lack of appetite or thirst.\nInfants may show symptoms like constant crying, excessive sleepiness, and a bulge in the soft spot on top of their heads.\nImmediate medical attention is critical.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Spotting Signs of Dehydration",
        "content": "Dehydration occurs when the body loses more fluids than it takes in.\nSymptoms range from mild to severe and include dry mouth and tongue, lack of tears when crying, sunken eyes, cheeks, and soft spot on the top of the skull in infants, lethargy, irritability, dark yellow urine, and in severe cases, very dry skin, dizziness, rapid heartbeat, rapid breathing, and fainting.\nRehydration through drinking fluids and, in severe cases, medical attention is necessary.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Identifying Symptoms of Shock",
        "content": "Shock is a life-threatening condition that occurs when the body is not getting enough blood flow.\nSymptoms include cool, clammy skin, pale or ashen skin, rapid pulse, rapid breathing, nausea or vomiting, enlarged pupils, weakness or fatigue, dizziness or fainting, and confusion or agitation.\nImmediate medical intervention is required to address the underlying cause and restore blood flow.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Recognizing Symptoms of Deep Vein Thrombosis (DVT)",
        "content": "Deep vein thrombosis (DVT) occurs when a blood clot forms in a deep vein, usually in the legs.\nSymptoms include swelling in one leg, leg pain or tenderness often described as a cramp or charley horse, red or discolored skin on the leg, and a feeling of warmth in the affected leg.\nIf the clot travels to the lungs, it can cause a pulmonary embolism, with symptoms like sudden shortness of breath, chest pain, and coughing up blood, requiring immediate emergency attention.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Detecting Signs of Appendicitis",
        "content": "Appendicitis is the inflammation of the appendix, a small tube attached to the large intestine.\nSymptoms include sudden pain that begins on the right side of the lower abdomen, sudden pain that begins around the navel and often shifts to the lower right abdomen, pain that worsens with movement, coughing, or jarring, nausea and vomiting, loss of appetite, low-grade fever, constipation or diarrhea, and abdominal bloating.\nImmediate surgical intervention is usually required.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Understanding Symptoms of Panic Attacks",
        "content": "A panic attack is a sudden episode of intense fear or anxiety and physical symptoms based on a perceived threat rather than imminent danger.\nSymptoms include a sense of impending doom or danger, fear of loss of control or death, rapid, pounding heart rate, sweating, trembling or shaking, shortness of breath or tightness in the throat, chills, hot flashes, nausea, abdominal cramping, chest pain, headache, dizziness, lightheadedness, or faintness, numbness or tingling sensation, and feeling of unreality or detachment.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Identifying Symptoms of Hypoglycemia (Low Blood Sugar)",
        "content": "Hypoglycemia, or low blood sugar, is a condition that occurs when blood sugar levels drop below normal.\nSymptoms include shakiness, nervousness or anxiety, sweating, chills, and clamminess, irritability or impatience, confusion, including delirium, rapid/fast heartbeat, lightheadedness or dizziness, hunger and nausea, sleepiness, blurred/impaired vision, tingling or numbness in the lips or tongue, headaches, weakness or fatigue, and in severe cases, seizures and unconsciousness.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Spotting Signs of Hyperglycemia (High Blood Sugar)",
        "content": "Hyperglycemia, or high blood sugar, occurs when there is too much glucose in the blood.\nSymptoms include frequent urination, increased thirst, blurred vision, fatigue, headache, and in more severe cases, fruity-smelling breath, nausea, vomiting, shortness of breath, dry mouth, weakness, confusion, and in extreme cases, diabetic coma.",
        "author": "HERS",
        "type": "edModule",
    },
    {
        "title": "Recognizing Symptoms of Internal Bleeding",
        "content": "Internal bleeding occurs when blood vessels inside the body are damaged.\nSymptoms include pain at the site of injury, swelling, skin discoloration, dizziness, fainting, low blood pressure, rapid pulse, and in severe cases, unconsciousness.\nImmediate medical intervention is necessary to control and stop the bleeding.",
        "author": "HERS",
        "type": "edModule",
    }
]
