export const firstaid = [
    {
        "title": "Clean a Wound",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Wash hands with soap and water\n- Rinse the wound with clean water\n- Apply antiseptic",
    },
    {
        "title": "Apply a Bandage",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Clean the wound\n- Dry the area around the wound\n- Place the bandage over the wound and secure it",
    },
    {
        "title": "Stop a Nosebleed",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Sit up straight and lean forward\n- Pinch the nostrils together\n- Hold for 10 minutes",
    },
    {
        "title": "Treat a Burn",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Cool the burn under running water for 10 minutes\n- Cover with a sterile dressing\n- Do not apply ice or ointments",
    },
    {
        "title": "Treat a Sprain",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Rest the injured area\n- Apply ice\n- Compress with an elastic bandage\n- Elevate the limb",
    },
    {
        "title": "Perform CPR",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Check for responsiveness\n- Call emergency services\n- Start chest compressions at a rate of 100-120 per minute",
    },
    {
        "title": "Remove a Splinter",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Clean the area with soap and water\n- Use tweezers to remove the splinter\n- Apply antiseptic",
    },
    {
        "title": "Treat an Insect Sting",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Remove the stinger if visible\n- Wash the area with soap and water\n- Apply ice to reduce swelling",
    },
    {
        "title": "Help with Choking",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Encourage the person to cough\n- Perform the Heimlich maneuver if coughing fails\n- Call emergency services if necessary",
    },
    {
        "title": "Relieve a Blister",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Clean the area with soap and water\n- Cover with a blister bandage\n- Do not pop the blister",
    },
    {
        "title": "Treat a Sunburn",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Cool the skin with damp cloths\n- Apply aloe vera gel\n- Drink plenty of fluids",
    },
    {
        "title": "Handle a Toothache",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Rinse mouth with warm water\n- Use dental floss to remove trapped food\n- Apply a cold compress to the cheek",
    },
    {
        "title": "Manage Heat Exhaustion",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Move to a cooler place\n- Drink cool water\n- Apply cool, wet cloths to the skin",
    },
    {
        "title": "Soothe a Cough",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Drink warm fluids\n- Use throat lozenges\n- Gargle with salt water",
    },
    {
        "title": "Deal with a Headache",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Rest in a quiet, dark room\n- Drink water\n- Apply a cold pack to the forehead",
    },
    {
        "title": "Treat a Bruise",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Apply ice to the area\n- Elevate the bruised area\n- Rest the affected area",
    },
    {
        "title": "Handle an Allergic Reaction",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Administer antihistamines\n- Apply a cold compress to the affected area\n- Call emergency services if symptoms worsen",
    },
    {
        "title": "Deal with Motion Sickness",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Sit in a stable position\n- Focus on the horizon\n- Take deep breaths",
    },
    {
        "title": "Soothe a Sore Throat",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Gargle with warm salt water\n- Drink warm tea with honey\n- Use throat lozenges",
    },
    {
        "title": "Treat an Eye Irritation",
        "type": "firstaid",
        "author": "HERS",
        "content": "- Rinse the eye with clean water\n- Avoid rubbing the eye\n- Use a sterile saline solution if available",
    }
]